version: '3.8'

services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  node:
    build:
      context: ./node
    ports:
      - "3000:3000"
    depends_on:
      - db

  php:
    build:
      context: ./php
    ports:
      - "80:80"
